name: musify
description: Music Streaming app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 9.7.5+154 # run update.sh after changing the version

environment:
  sdk: '>=3.9.10 <4.0.0'
  flutter: ^3.38.5

dependencies:
  app_links: ^7.0.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  cached_network_image: ^3.4.1
  dynamic_color: ^1.8.1
  file_picker: ^10.3.7
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.6.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  just_audio: 0.10.5
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  youtube_explode_dart: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.1.0

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf
