name: musify
description: Music Streaming app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 9.1.0+114 # run update.sh after changing the version

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ^3.29.0

dependencies:
  audio_service: ^0.18.17
  audio_session: ^0.1.25
  cached_network_image: ^3.4.1
  dynamic_color: ^1.7.0
  file_picker: ^8.3.7
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.5
  http: ^1.3.0
  intl: ^0.19.0
  just_audio: ^0.9.46
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  youtube_explode_dart: ^2.3.9

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

flutter_native_splash:
  color: '#f9fafd'
  image: assets/images/ic_splash.png
  color_dark: '#151515'
  image_dark: assets/images/ic_splash.png

  android_12:
    image: assets/images/ic_splash.png
    image_dark: assets/images/ic_splash.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  adaptive_icon_monochrome: 'assets/images/ic_launcher_foreground.png'
  image_path: 'assets/images/ic_launcher.png'
