name: audio_service_platform_interface
description: A common platform interface for the audio_service plugin. Different platform implementations of audio_service should implement this interface.
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  flutter_lints: ^1.0.4
  build_runner: ^2.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
