name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.18.10
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  # Use these deps for local development
  # audio_service_platform_interface:
  #   path: ../audio_service_platform_interface
  # audio_service_web:
  #   path: ../audio_service_web

  # Use these deps when pushing to origin (for the benefit of testers)
  # audio_service_platform_interface:
  #   git:
  #     url: https://github.com/ryanheise/audio_service.git
  #     ref: one-isolate
  #     path: audio_service_platform_interface
  # audio_service_web:
  #   git:
  #     url: https://github.com/ryanheise/audio_service.git
  #     ref: one-isolate
  #     path: audio_service_web

  # Use these deps when publishing.
  audio_service_platform_interface: ^0.1.0
  audio_service_web: ^0.1.1

  audio_session: ^0.1.6+1
  rxdart: '>=0.26.0 <0.28.0'
  flutter_cache_manager: ^3.0.1
  clock: ^1.1.0
  js: ^0.6.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  fake_async: ^1.2.0
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audioservice
        pluginClass: AudioServicePlugin
      ios:
        pluginClass: AudioServicePlugin
      macos:
        pluginClass: AudioServicePlugin
      web:
        default_package: audio_service_web
