# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/
# ========
name: on_audio_query
description: Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage.
version: 2.9.0
homepage: https://github.com/LucJosin/on_audio_query/tree/main/packages/on_audio_query
issue_tracker: https://github.com/LucJosin/on_audio_query/issues
# pub.dev: https://pub.dev/packages/on_audio_query
topics:
  - audio
  - song
  - audioquery
  - on-audio-query
  - storage
  - mediastore
  - mpmediaquery

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface: ^1.7.0
  on_audio_query_web: ^1.6.0
  on_audio_query_ios: ^1.1.0
  on_audio_query_android:
    path: ./on_audio_query_android-1.1.0

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Design
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: on_audio_query_android
      ios:
        default_package: on_audio_query_ios
      web:
        default_package: on_audio_query_web
